#' CLD
#' A data package for CLD.
#' @docType package
#' @aliases CLD-package
#' @title CLD -- The Chinese Lexical Database
#' @name CLD
#' @description This package contains the Chinese Lexical Database CLD
#' @details Use \code{data(package='CLD')$results[, 3]} to see a list of available data sets in this data package
#'     and/or DataPackageR::load_all
#' _datasets() to load them.
#' @seealso
#' \link{cld}
NULL




#' Detailed description of the data
#' @name cld
#' @docType data
#' @title The Chinese Lexical Database (CLD)
#' @format a \code{data.frame} containing the following fields:
#' \describe{
#' \item{Word}{}
#' \item{C1}{}
#' \item{C2}{}
#' \item{C3}{}
#' \item{C4}{}
#' \item{Length}{}
#' \item{C1Structure}{}
#' \item{C2Structure}{}
#' \item{C3Structure}{}
#' \item{C4Structure}{}
#' \item{C1Type}{}
#' \item{C2Type}{}
#' \item{C3Type}{}
#' \item{C4Type}{}
#' \item{Pinyin}{}
#' \item{C1Pinyin}{}
#' \item{C2Pinyin}{}
#' \item{C3Pinyin}{}
#' \item{C4Pinyin}{}
#' \item{IPA}{}
#' \item{C1IPA}{}
#' \item{C2IPA}{}
#' \item{C3IPA}{}
#' \item{C4IPA}{}
#' \item{InitialPhoneme}{}
#' \item{FinalPhoneme}{}
#' \item{C1PRPinyin}{}
#' \item{C2PRPinyin}{}
#' \item{C3PRPinyin}{}
#' \item{C4PRPinyin}{}
#' \item{Phonemes}{}
#' \item{C1Phonemes}{}
#' \item{C2Phonemes}{}
#' \item{C3Phonemes}{}
#' \item{C4Phonemes}{}
#' \item{C1Tone}{}
#' \item{C2Tone}{}
#' \item{C3Tone}{}
#' \item{C4Tone}{}
#' \item{Frequency}{}
#' \item{C1Frequency}{}
#' \item{C2Frequency}{}
#' \item{C3Frequency}{}
#' \item{C4Frequency}{}
#' \item{FrequencyRaw}{}
#' \item{C1FrequencyRaw}{}
#' \item{C2FrequencyRaw}{}
#' \item{C3FrequencyRaw}{}
#' \item{C4FrequencyRaw}{}
#' \item{FrequencySUBTL}{}
#' \item{C1FrequencySUBTL}{}
#' \item{C2FrequencySUBTL}{}
#' \item{C3FrequencySUBTL}{}
#' \item{C4FrequencySUBTL}{}
#' \item{FrequencyRawSUBTL}{}
#' \item{C1FrequencyRawSUBTL}{}
#' \item{C2FrequencyRawSUBTL}{}
#' \item{C3FrequencyRawSUBTL}{}
#' \item{C4FrequencyRawSUBTL}{}
#' \item{FrequencyWeibo}{}
#' \item{C1FrequencyWeibo}{}
#' \item{C2FrequencyWeibo}{}
#' \item{C3FrequencyWeibo}{}
#' \item{C4FrequencyWeibo}{}
#' \item{FrequencyRawWeibo}{}
#' \item{C1FrequencyRawWeibo}{}
#' \item{C2FrequencyRawWeibo}{}
#' \item{C3FrequencyRawWeibo}{}
#' \item{C4FrequencyRawWeibo}{}
#' \item{PhonologicalFrequency}{}
#' \item{C1PhonologicalFrequency}{}
#' \item{C2PhonologicalFrequency}{}
#' \item{C3PhonologicalFrequency}{}
#' \item{C4PhonologicalFrequency}{}
#' \item{C1FamilySize}{}
#' \item{C2FamilySize}{}
#' \item{C3FamilySize}{}
#' \item{C4FamilySize}{}
#' \item{C1FamilyFrequency}{}
#' \item{C2FamilyFrequency}{}
#' \item{C3FamilyFrequency}{}
#' \item{C4FamilyFrequency}{}
#' \item{Strokes}{}
#' \item{C1Strokes}{}
#' \item{C2Strokes}{}
#' \item{C3Strokes}{}
#' \item{C4Strokes}{}
#' \item{C1Pixels}{}
#' \item{C2Pixels}{}
#' \item{C3Pixels}{}
#' \item{C4Pixels}{}
#' \item{C1PictureSize}{}
#' \item{C2PictureSize}{}
#' \item{C3PictureSize}{}
#' \item{C4PictureSize}{}
#' \item{C1OLDPixels}{}
#' \item{C2OLDPixels}{}
#' \item{C3OLDPixels}{}
#' \item{C4OLDPixels}{}
#' \item{PhonologicalN}{}
#' \item{C1PhonologicalN}{}
#' \item{C2PhonologicalN}{}
#' \item{C3PhonologicalN}{}
#' \item{C4PhonologicalN}{}
#' \item{PLD}{}
#' \item{C1PLD}{}
#' \item{C2PLD}{}
#' \item{C3PLD}{}
#' \item{C4PLD}{}
#' \item{C1SR}{}
#' \item{C2SR}{}
#' \item{C3SR}{}
#' \item{C4SR}{}
#' \item{C1SRFrequency}{}
#' \item{C2SRFrequency}{}
#' \item{C3SRFrequency}{}
#' \item{C4SRFrequency}{}
#' \item{C1SRFamilySize}{}
#' \item{C2SRFamilySize}{}
#' \item{C3SRFamilySize}{}
#' \item{C4SRFamilySize}{}
#' \item{C1SRStrokes}{}
#' \item{C2SRStrokes}{}
#' \item{C3SRStrokes}{}
#' \item{C4SRStrokes}{}
#' \item{C1PR}{}
#' \item{C2PR}{}
#' \item{C3PR}{}
#' \item{C4PR}{}
#' \item{C1PRFrequency}{}
#' \item{C2PRFrequency}{}
#' \item{C3PRFrequency}{}
#' \item{C4PRFrequency}{}
#' \item{C1PRFamilySize}{}
#' \item{C2PRFamilySize}{}
#' \item{C3PRFamilySize}{}
#' \item{C4PRFamilySize}{}
#' \item{C1PRStrokes}{}
#' \item{C2PRStrokes}{}
#' \item{C3PRStrokes}{}
#' \item{C4PRStrokes}{}
#' \item{C1PRRegularity}{}
#' \item{C2PRRegularity}{}
#' \item{C3PRRegularity}{}
#' \item{C4PRRegularity}{}
#' \item{C1PRFriends}{}
#' \item{C2PRFriends}{}
#' \item{C3PRFriends}{}
#' \item{C4PRFriends}{}
#' \item{C1PREnemiesTypes}{}
#' \item{C2PREnemiesTypes}{}
#' \item{C3PREnemiesTypes}{}
#' \item{C4PREnemiesTypes}{}
#' \item{C1PREnemiesTokens}{}
#' \item{C2PREnemiesTokens}{}
#' \item{C3PREnemiesTokens}{}
#' \item{C4PREnemiesTokens}{}
#' \item{C1PRFriendsFrequency}{}
#' \item{C2PRFriendsFrequency}{}
#' \item{C3PRFriendsFrequency}{}
#' \item{C4PRFriendsFrequency}{}
#' \item{C1PREnemiesFrequency}{}
#' \item{C2PREnemiesFrequency}{}
#' \item{C3PREnemiesFrequency}{}
#' \item{C4PREnemiesFrequency}{}
#' \item{C1PRBackwardEnemiesTypes}{}
#' \item{C2PRBackwardEnemiesTypes}{}
#' \item{C3PRBackwardEnemiesTypes}{}
#' \item{C4PRBackwardEnemiesTypes}{}
#' \item{C1PRBackwardEnemiesTokens}{}
#' \item{C2PRBackwardEnemiesTokens}{}
#' \item{C3PRBackwardEnemiesTokens}{}
#' \item{C4PRBackwardEnemiesTokens}{}
#' \item{C1PRBackwardEnemiesFrequency}{}
#' \item{C2PRBackwardEnemiesFrequency}{}
#' \item{C3PRBackwardEnemiesFrequency}{}
#' \item{C4PRBackwardEnemiesFrequency}{}
#' \item{MeanPhonemeFrequency}{}
#' \item{C1MeanPhonemeFrequency}{}
#' \item{C2MeanPhonemeFrequency}{}
#' \item{C3MeanPhonemeFrequency}{}
#' \item{C4MeanPhonemeFrequency}{}
#' \item{MinPhonemeFrequency}{}
#' \item{C1MinPhonemeFrequency}{}
#' \item{C2MinPhonemeFrequency}{}
#' \item{C3MinPhonemeFrequency}{}
#' \item{C4MinPhonemeFrequency}{}
#' \item{MaxPhonemeFrequency}{}
#' \item{C1MaxPhonemeFrequency}{}
#' \item{C2MaxPhonemeFrequency}{}
#' \item{C3MaxPhonemeFrequency}{}
#' \item{C4MaxPhonemeFrequency}{}
#' \item{C1InitialPhonemeFrequency}{}
#' \item{C2InitialPhonemeFrequency}{}
#' \item{C3InitialPhonemeFrequency}{}
#' \item{C4InitialPhonemeFrequency}{}
#' \item{MeanDiphoneFrequency}{}
#' \item{C1MeanDiphoneFrequency}{}
#' \item{C2MeanDiphoneFrequency}{}
#' \item{C3MeanDiphoneFrequency}{}
#' \item{C4MeanDiphoneFrequency}{}
#' \item{MinDiphoneFrequency}{}
#' \item{C1MinDiphoneFrequency}{}
#' \item{C2MinDiphoneFrequency}{}
#' \item{C3MinDiphoneFrequency}{}
#' \item{C4MinDiphoneFrequency}{}
#' \item{MaxDiphoneFrequency}{}
#' \item{C1MaxDiphoneFrequency}{}
#' \item{C2MaxDiphoneFrequency}{}
#' \item{C3MaxDiphoneFrequency}{}
#' \item{C4MaxDiphoneFrequency}{}
#' \item{C1InitialDiphoneFrequency}{}
#' \item{C2InitialDiphoneFrequency}{}
#' \item{C3InitialDiphoneFrequency}{}
#' \item{C4InitialDiphoneFrequency}{}
#' \item{TransitionalDiphone1Frequency}{}
#' \item{TransitionalDiphone2Frequency}{}
#' \item{TransitionalDiphone3Frequency}{}
#' \item{C1Friends}{}
#' \item{C2Friends}{}
#' \item{C3Friends}{}
#' \item{C4Friends}{}
#' \item{C1HomographTypes}{}
#' \item{C2HomographTypes}{}
#' \item{C3HomographTypes}{}
#' \item{C4HomographTypes}{}
#' \item{C1HomographTokens}{}
#' \item{C2HomographTokens}{}
#' \item{C3HomographTokens}{}
#' \item{C4HomographTokens}{}
#' \item{C1FriendsFrequency}{}
#' \item{C2FriendsFrequency}{}
#' \item{C3FriendsFrequency}{}
#' \item{C4FriendsFrequency}{}
#' \item{C1HomographsFrequency}{}
#' \item{C2HomographsFrequency}{}
#' \item{C3HomographsFrequency}{}
#' \item{C4HomographsFrequency}{}
#' \item{C1HomophoneTypes}{}
#' \item{C2HomophoneTypes}{}
#' \item{C3HomophoneTypes}{}
#' \item{C4HomophoneTypes}{}
#' \item{C1HomophoneTokens}{}
#' \item{C2HomophoneTokens}{}
#' \item{C3HomophoneTokens}{}
#' \item{C4HomophoneTokens}{}
#' \item{C1HomophonesFrequency}{}
#' \item{C2HomophonesFrequency}{}
#' \item{C3HomophonesFrequency}{}
#' \item{C4HomophonesFrequency}{}
#' \item{C1Entropy}{}
#' \item{C12Entropy}{}
#' \item{C123Entropy}{}
#' \item{C1BackwardEntropy}{}
#' \item{C12BackwardEntropy}{}
#' \item{C123BackwardEntropy}{}
#' \item{C1RE}{}
#' \item{C2RE}{}
#' \item{PMI}{}
#' \item{PSPMI}{}
#' \item{TScore}{}
#' \item{PSTScore}{}
#' \item{C1ConditionalProbability}{}
#' \item{C12ConditionalProbability}{}
#' \item{C123ConditionalProbability}{}
#' \item{C1BackwardConditionalProbability}{}
#' \item{C12BackwardConditionalProbability}{}
#' \item{C123BackwardConditionalProbability}{}
#' \item{EntropyCharacterFrequencies}{}
#' }
#' @source The data comes from http://www.chineselexicaldatabase.com.
#' @seealso
#' \link{CLD}
NULL
